# Generated by Django 4.2.2 on 2024-06-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0002_alter_user_managers_remove_user_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Token"
            ),
        ),
    ]
