# Generated by Django 4.2.2 on 2024-06-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0003_user_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="id"),
        ),
    ]
