# Generated by Django 4.2.2 on 2024-06-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0004_user_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.IntegerField(),
        ),
    ]
