# Generated by Django 4.2.2 on 2024-06-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0005_alter_user_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_id",
        ),
    ]
