# Generated by Django 4.2.2 on 2024-06-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0006_remove_user_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="состояние активности пользователя"
            ),
        ),
    ]
