# Generated by Django 4.2.2 on 2024-06-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0007_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (
                    ("can_view_users", "Can view users"),
                    ("can_edit_is_active", "Can edit active users"),
                ),
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
