# Generated by Django 4.2.2 on 2024-06-15 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите Ф.И.О.",
                        max_length=100,
                        verbose_name="Ф.И.О.",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Введите комментарий",
                        max_length=255,
                        null=True,
                        verbose_name="комментарий",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "letter_subject",
                    models.CharField(max_length=255, verbose_name="тема письма"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="ссылка"
                    ),
                ),
                ("letter_body", models.TextField(verbose_name="тело письма")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users_app.user",
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
        migrations.CreateModel(
            name="SendingMailSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите имя рассылки",
                        max_length=255,
                        verbose_name="имя рассылки",
                    ),
                ),
                (
                    "first_sending_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="дата первой отправки"
                    ),
                ),
                (
                    "sending_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="время отправки"
                    ),
                ),
                (
                    "sending_period",
                    models.CharField(
                        choices=[
                            ("one_in_month", "один раз в месяц"),
                            ("one_in_week", "один раз в неделю"),
                            ("one_in_day", "один раз в день"),
                        ],
                        default="one_in_week",
                        max_length=13,
                        verbose_name="период отправки",
                    ),
                ),
                (
                    "sending_status",
                    models.CharField(
                        choices=[
                            ("completed", "завершена"),
                            ("created", "создана"),
                            ("running", "выполняется"),
                        ],
                        default="created",
                        max_length=9,
                        verbose_name="статус отправки",
                    ),
                ),
                (
                    "client_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing_interface_app.clientservice",
                        verbose_name="клиент",
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing_interface_app.message",
                        verbose_name="сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.CreateModel(
            name="SendTry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sending_status",
                    models.CharField(
                        choices=[("SUCCESS", "успешно"), ("FAILURE", "неудачно")],
                        default="FAILURE",
                        max_length=7,
                        verbose_name="статус попытки отправки",
                    ),
                ),
                (
                    "last_sending_date",
                    models.DateTimeField(
                        verbose_name="дата последней попытки отправки"
                    ),
                ),
                (
                    "server_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="ответ почтового сервера"
                    ),
                ),
                (
                    "client_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing_interface_app.clientservice",
                        verbose_name="клиент",
                    ),
                ),
                (
                    "sending_mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing_interface_app.sendingmailset",
                        verbose_name="отправка",
                    ),
                ),
            ],
            options={
                "verbose_name": "попытка отправки",
                "verbose_name_plural": "попытки отправки",
            },
        ),
    ]
