# Generated by Django 4.2.2 on 2024-06-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_interface_app", "0002_alter_clientservice_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="ссылка",
            ),
        ),
    ]
