# Generated by Django 4.2.2 on 2024-06-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_interface_app", "0003_alter_message_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sendingmailset",
            name="sending_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="время отправки"
            ),
        ),
    ]
