# Generated by Django 4.2.2 on 2024-06-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_interface_app", "0007_alter_sendingmailset_first_sending_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sendtry",
            name="client_service",
        ),
        migrations.AlterField(
            model_name="sendingmailset",
            name="first_sending_date",
            field=models.DateTimeField(
                help_text="Введите дату и время отправки в формате ДД.ММ.ГГГГ 00:00:00",
                verbose_name="дата первой отправки",
            ),
        ),
        migrations.AlterField(
            model_name="sendtry",
            name="last_sending_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="дата последней попытки отправки"
            ),
        ),
    ]
