# Generated by Django 4.2.2 on 2024-06-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_interface_app", "0008_remove_sendtry_client_service_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sendingmailset",
            name="sending_time",
        ),
        migrations.AddField(
            model_name="sendingmailset",
            name="next_sending_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="дата и время следующей отправки"
            ),
        ),
    ]
