# Generated by Django 4.2.2 on 2024-06-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_interface_app", "0009_remove_sendingmailset_sending_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sendtry",
            old_name="sending_status",
            new_name="status",
        ),
    ]
