# Generated by Django 4.2.2 on 2024-06-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_interface_app", "0010_rename_sending_status_sendtry_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sendingmailset",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="состояние активности рассылки"
            ),
        ),
    ]
