# Generated by Django 4.2.2 on 2024-06-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_interface_app", "0011_sendingmailset_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sendingmailset",
            options={
                "permissions": (
                    ("can_view_sending_mail_set", "Can view sending mail set"),
                    ("can_edit_is_active", "Can edit active sending mail set"),
                ),
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
