# Generated by Django 4.2.2 on 2024-06-21 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "блог", "verbose_name_plural": "блоги"},
        ),
        migrations.AddField(
            model_name="blog",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="укажите владельца рассылки",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
    ]
