# Generated by Django 4.2.2 on 2024-06-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0002_alter_blog_options_blog_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="published_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата публикации"
            ),
        ),
    ]
